### ISSUE TITLE
No success on Pi 1 B+

### ISSUE THREAD

**Issue by Abrastreve** [PiDrive/CommunityFoundationEdition#1]
For me this Stretch version NOOBS works well on my Pi2 B+ but fails on the P1 B+.
At startup it gives various error messages that have to do with the USB dongle for the keyboard or refer to the USB mouse. The NOOBS screen is then displayed but the Pi does not respond to keyboard or mouse input anymore.

**Comment by Nilpo** [comment]
This probably has something to do with the kernel drivers. Let me do a little research and see what has changed since RPi 1. This issue might need to be added to the NOOBS repository since much of the code is closed source.

**Comment by Abrastreve** [comment]
The latest version of the Community Foundation Edition (pidrive-cfe-20180502) turns out to work as expected. Thanks for all te effort that has gone in to the creation of this CFE and making it available to the community.

**Comment by Nilpo** [comment]
You're welcome. I'm glad you are finding it useful!
