### ISSUE TITLE
Going to PI 3b+ from 3B

### ISSUE THREAD

**Issue by sgrayban** [PiDrive/CommunityFoundationEdition#3]
How can I upgrade the sd card from 3B to 3B+ without killing my hard drive partitions ?

**Comment by Nilpo** [comment]
The project includes firmware support for the 3B+ already.

**Comment by sgrayban** [comment]
Yes I understand that.

Currently I am using a 3B and want to switch to the 3B+ but I dont want to go through a fresh install again so how do I avoid that ?

**Comment by sgrayban** [comment]
I'm trying to figure out how to update PI drive noobs without having to reinstall and NOT nuke my hard drive.

**Comment by Nilpo** [comment]
You need to add the updated firmware files to the boot partition without touching the storage partitions. You can download the firmware from the RPi Foundation website.

**Comment by sgrayban** [comment]
excellent !

**Comment by Nilpo** [comment]
If you're willing to run the beta firmware, you can also boot into Raspbian and run the `rpi-update` script. Keep in mind that the beta firmware is bleeding edge and may not be stable in all cases.

**Comment by sgrayban** [comment]
Ya I knew that but I don't think that's a good idea.

I don't understand why the Raspberry devs wanted to use beta software to update with rpi-update. As a matter of fact when you run it it doesn't tell you its installing beta code.

I wonder if I can make a script that will use the stable version instead....

**Comment by sgrayban** [comment]
hmmm I wonder if you did a reinstall of raspberrypi-bootloader it would accomplish the same thing but use the current stable version ?

**Comment by Nilpo** [comment]
The `rpi-update` script is on GitHub. Take a look at it.
