### ISSUE TITLE
Pi 4 support ??

### ISSUE THREAD

**Issue by sgrayban** [PiDrive/CommunityFoundationEdition#4]
Will the code get updated for the new PI 4 ?

**Comment by Nilpo** [comment]
Sure. I'll try to push an update today.

**Comment by sgrayban** [comment]
Thanks !

**Comment by sgrayban** [comment]
Any news on this ?

**Comment by Nilpo** [comment]
The update is in progress. The build and upload take quite a bit of time due to the file sizes involved.

**Comment by Nilpo** [comment]
All set. Updated Raspbian to the latest version and added firmware for the RPi 4.

**Comment by sgrayban** [comment]
AWESOME !!! Thank you !!
