### ISSUE TITLE
Pi does not start

### ISSUE THREAD

**Issue by sdk69** [PiDrive/CommunityFoundationEdition#5]
Hello,

I have download and unzipped the archive on my FAT 32 formatted SD card, however when I start the raspberry pi, nothing happens, screen stays black and it does not connect to my router so I can't do anything with putty either.

I noticed that the original SD car I received with the pidrive has several partitions and the file structure is not exactly the same as the archive I downloaded from this project.

I have a rapsberry pi 3.

Am I missing something ? Do I also need several partitions and to change a bit the folder of this archive ?

Thank you so much for your work!

Rom

**Comment by sdk69** [comment]
I am such a noob myself, didn't noticed that I needed to only take the "latest" folder on the SD. It works perfectly, this is great work. Thanks

**Comment by emmercm** [comment]
I don't see this instruction in the README though, I don't think this is obvious at all.
