### ISSUE TITLE
Dedicated hard disk

### ISSUE THREAD

**Issue by kart-able** [PiDrive/CommunityFoundationEdition#6]
Wether a dedicated hard disk is needed or can I test this software with 1 (or 2) partition on a HDD that contains data already? Eventually what format would be required? FAT32 or EXT4?

**Comment by Nilpo** [comment]
You can use partitioning, but you will need to be very careful and might need to modify the scripts. I would highly recommend against doing it this way until you've tried it with a bare HDD and understand how everything works. Any Linux-readable file system works, but be aware of file size- and partition-size limitations.

**Comment by kart-able** [comment]
It's good to know but I am just a noob trying hard to understand. At least I know there is some hope in this direction. Thanks.
