### ISSUE TITLE
Boot problems with RasPi 2B+, now fixed

### ISSUE THREAD

**Issue by G3O-CH** [PiDrive/CommunityFoundationEdition#7]
I downloaded the zip-file from github, extracted and copied it to the SD-card, and nothing happened, not even an error!
To prevent that this could be a hardware-failure, I downloaded and extracted the NOOBS-file, and this worked (on the SD. not on the SSD).
I am only an experienced user and not a programmer, but I have the intention that the minimalistic hardware and firmware from the RasPi 2B+ is not able to search executable files in the depth of the file system.
So I copied only the files of the folder "latest" (and its subfolders) from the pidrive-cfe-20190804 to the SD, and it worked perfectly.

This is my workaround, perhaps it helps other people.

Best regards
Christopher

**Comment by Nilpo** [comment]
@G3O-CH  Sorry. The last build was incorrect. It should only contain the "latest" folder contents so that it can be extracted directly to the SD card.

I have corrected this issue and have updated to the latest available NOOBS software and the latest release of Raspbian.
