### ISSUE TITLE
Broken download-link

### ISSUE THREAD

**Issue by G3O-CH** [PiDrive/CommunityFoundationEdition#8]
@G3O-CH  ...

I have corrected this issue and have updated to the latest available NOOBS software and the latest release of Raspbian.

_Originally posted by @Nilpo in https://github.com/PiDrive/CommunityFoundationEdition/issues/7#issuecomment-732117964_

**Comment by G3O-CH** [comment]
Thank you for the update, but there is something wrong.
Clicking on the download-link gets:
""This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E126482A03D02715</RequestId>
<HostId>IKiArO/J1kuIamMlIZVYO3xkefGzZSLyCUkYqMQVA3ci9qbf0SFt0Zej/Yqy+NoXU5mNHM6flII=</HostId>
</Error>

Best regards, Christopher

**Comment by sgrayban** [comment]
Ditto..

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9389BC0DBC4431C3</RequestId>
<HostId>fehigz+Fb5SzyxhClefHUfzmFmb+8iWU94xuDDlRrE0FyclTgeoRTfRvWeEZTvBUPCXjUosYjUM=</HostId>
</Error>
```

**Comment by Nilpo** [comment]
The update is still in progress. It takes a couple of hours to upload to Amazon AWS. There's about 30 minutes left.

**Comment by Nilpo** [comment]
@G3O-CH @sgrayban The new file uploads have completed. Enjoy!

**Comment by Nilpo** [comment]
I'd also be like your opinions on Issue #9 if you have time.
